# Generated by Django 5.0 on 2024-10-16 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_event_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.seat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default='2000-01-01 00:00', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='Untitled Event', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='event',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.event'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
