# Generated by Django 5.0 on 2024-10-17 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_name_alter_booking_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booked_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.event'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
